### ISSUE TITLE
Replace placekitten with image of actual sky. trees etc

### ISSUE THREAD

**Issue by tomoinn** [camsci/meteor-pi#51]
The region editor uses a placekitten, this should be replaced with an appropriate image from the database (as and when it has one). Trivial to do, just need to insert the appropriate query into the camera status editor page and set the image URL for the region editor, but we need to work out the appropriate query.

**Comment by dcf21** [comment]
I'd be inclined to pick the latest image with semantic type `meteorpi:timelapse/frame`.

That will usually give you a dawn image with no stars visible, but a crisp picture of any foreground objects.

An alternative would be to pick the image of that semantic type with the highest `skyClarity` value. On a good day that might give you a pretty starry sky, but unilluminated foreground objects may not show up very well.

You don't want to use the images of type `meteorpi:timelapse/frame/bgrdSub` because they have been processed to remove the sky background, which tends to make trees and houses invisible.

**Comment by dcf21** [comment]
You need to use images without `/lensCorr` in their semantic types. These images have had barrel distortion corrected, so image coordinates don't correspond the those in the raw video.

The sample database I gave you doesn't have any images without lens correction (as I figured they were mostly just a waste of disk space). I should set my code to spit one out every few minutes.
